---
- name: Ensure project root exists
  ansible.builtin.file:
    path: "{{ project_root }}"
    state: directory
    mode: '0755'
  tags:
    - clone

- name: Clone or update repositories
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ project_root }}/{{ item | basename | regex_replace('.git','') }}"
    version: main
    key_file: "{{ ssh_key_path }}"
    update: yes
    force: yes
    accept_hostkey: yes
  loop: "{{ github_repos }}"
  tags:
    - clone
